### ISSUE TITLE
When installed shows as "Unknown"

### ISSUE THREAD

**Issue by derekpurdy** [jneilliii/OctoPrint-PSUControl-Wemo#2]
#### What were you doing?

1. Installed from within Octoprint
2. Installed from GitHub URL

#### What did you expect to happen?

Should install and be available.

#### What happened instead?

- The installer dialog shows "Successfully installed OctoPrint-PSUControl-Wemo-1.0.1"

- Popup showed

"Plugin management log
Install Unknown: 
A restart is needed for the changes to take effect."

- Does not appear in Installed Plugins

#### Version of OctoPrint-PSUControl

1.0.6

#### Version of OctoPrint-PSUControl-Wemo

1.0.0 or 1.0.1

#### Operating System running OctoPrint

OctoPi

**Comment by jneilliii** [comment]
This could be a python or system dependency issue. Please share complete octoprint.log.

**Comment by derekpurdy** [comment]
Thanks. I checked the log... saw an error for libxslt, manually installed it and the plugin shows up now.
